server:
  port: 8087

spring:
  application:
    name: frontend-thymeleaf
  config:
    import: optional:configserver:http://localhost:8888/
#  thymeleaf:
#    cache: false
#
#gateway:
#  url: http://localhost:8080
#
#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#    register-with-eureka: true
#    fetch-registry: true
#  instance:
#    prefer-ip-address: true
